[package]
name = "polywrap_client"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
thiserror = "1.0.37"
async-trait = "0.1.57"
futures = "0.3.24"
polywrap_core = {path = "../core"}
polywrap_msgpack = {path = "../msgpack"}
polywrap_tests_utils = {path = "../tests-utils"}
polywrap_plugin = {path ="../plugin"}
fs_resolver_plugin = {path = "../plugins/fs-resolver"}
filesystem_plugin = {path = "../plugins/fs"}
http_resolver_plugin = {path = "../plugins/http-resolver"}
http_plugin = {path = "../plugins/http"}
serde = {version = "1.0.145", features = ["derive"]}
serde_json = "1.0.87"

[dev-dependencies]
polywrap_resolvers = {path = "../resolvers"}
tokio = { version = "1.3", features = ["full"] }