[package]
name = "polywrap_client"
description = "Polywrap Client implementation in rust"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
polywrap_core.workspace = true
polywrap_msgpack.workspace = true
polywrap_resolvers.workspace = true
polywrap_client_builder.workspace = true
polywrap_wasm.workspace = true
polywrap_plugin.workspace = true
wrap_manifest_schemas.workspace = true
polywrap_core_macros.workspace = true

thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
rmp-serde.workspace = true
serde_bytes.workspace = true

[dev-dependencies]
polywrap_tests_utils.workspace = true
bigdecimal.workspace = true
num-bigint.workspace = true