[package]
name = "polywrap_client"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
thiserror = "1.0.37"
polywrap_core = {path = "../core"}
polywrap_msgpack = {path = "../msgpack"}
serde = {version = "1.0.145", features = ["derive"]}
serde_json = "1.0.87"

[dev-dependencies]
polywrap_client_builder = {path = "../builder"}
polywrap_resolvers = {path = "../resolvers"}
polywrap_wasm = {path = "../wasm"}
polywrap_tests_utils = {path = "../tests-utils"}
wrap_manifest_schemas = {path = "../manifest"}
