[workspace.package]
version = "0.1.6-beta.1"
license = "MIT"
edition = "2021"
rust-version = "1.67"
repository = "https://github.com/polywrap/rust-client"

[workspace]
members = [
    "packages/client",
    "packages/core",
    "packages/wasm",
    "packages/native",
    "packages/resolvers",
    "packages/msgpack",
    "packages/manifest",
    "packages/builder",
    "packages/plugin",
    "packages/tests-utils",
    "packages/default-config"
]

# Do not include test utils & default config crates in default members
default-members = [
    "packages/client",
    "packages/core",
    "packages/wasm",
    "packages/resolvers",
    "packages/msgpack",
    "packages/manifest",
    "packages/builder",
    "packages/plugin",
]

[workspace.dependencies]
polywrap_client = { version = "0.1.6-beta.1", path = "packages/client" } 
polywrap_wasm = { version = "0.1.6-beta.1", path = "packages/wasm" }
polywrap_client_builder = { version = "0.1.6-beta.1", path = "packages/builder" }
polywrap_core = { version = "0.1.6-beta.1", path = "packages/core" }
wrap_manifest_schemas = { version = "0.1.6-beta.1", path = "packages/manifest" }
polywrap_resolvers = { version = "0.1.6-beta.1", path = "packages/resolvers" }
polywrap_msgpack = { version = "0.1.6-beta.1", path = "packages/msgpack" }
polywrap_tests_utils = { version = "0.1.6-beta.1", path = "packages/tests-utils" }
polywrap_plugin = { version = "0.1.6-beta.1", path = "packages/plugin" }

polywrap_plugin_implementor = { version = "0.1.6-beta.1", path = "packages/plugin/implementor" }

serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.37"
jsonschema = "0.16.1"
regex = "1.6.0"
rmp-serde = "1.1.1"

proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0.105", features=["full", "extra-traits", "visit"] }
base64 = "0.13.1"
