[package]
name = "polywrap_ffi_client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
polywrap_client = {path = "../client"}
polywrap_core = {path = "../core"}
polywrap_resolvers = {path = "../resolvers"}
futures = "0.3.24"
polywrap_plugin = {path ="../plugin"}
fs_resolver_plugin = {path = "../plugins/fs-resolver"}
filesystem_plugin = {path = "../plugins/fs"}
http_resolver_plugin = {path = "../plugins/http-resolver"}
http_plugin = {path = "../plugins/http"}
jni = "0.20.0"
# openssl = { version = "0.10.43", features = ["vendored"] }
rmp-serde = "1.1.1"
polywrap_msgpack = {path = "../msgpack"}
serde_json = "1.0.87"
android_logger = "0.11"
log = "0.4.17"