[package]
name = "polywrap_manifest"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.37"
polywrap_core = {path = "../core"}
polywrap_msgpack = {path = "../msgpack"}
serde = {version = "1.0.145", features = ["derive"]}
serde_json = "1.0.87"
serde_yaml = "0.9.14"
semver = "1.0.14"
jsonschema = "0.16.1"
polywrap_schemafy = "0.1.1"

[build-dependencies]
thiserror = "1.0.37"
handlebars = "4.3.5"
semver = "1.0.14"
serde_json = "1.0"
polywrap-jsonref = "0.1.0"
serde = {version = "1.0.145", features = ["derive"]}
ureq = "2.3.0"