[package]
name = "polywrap_client_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
polywrap_core = {path = "../core"}
polywrap_resolvers = { path = "../resolvers" }
serde_json = "1.0.87"
serde = {version = "1.0.145", features = ["derive"]}

[dev-dependencies]
mockall = "0.11.2"
actix-rt = "*"